on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule: # minute hour
    - cron: '25 5 * * *'
    - cron: '25 10 * * *'
permissions:
  contents: write
jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::httr 
            any::jsonlite
            any::dplyr
            any::readr
            any::stringr
            any::purrr
            
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_TOKEN }}

      - name: Import data
        run: Rscript -e 'source("getdata.R")'

      - name: Commit results
        run: |
          git config --global user.email "andrew.cooper@seattlechildrens.org"
          git config --global user.name "sch-data-science"
          git add trials.RDS
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
